// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFARMbet950EVGuekismUM0wDp3knFkQ',
    appId: '1:26260141407:web:d27eb7d3ea542f5bf532ea',
    messagingSenderId: '26260141407',
    projectId: 'shopping-app-cdbe4',
    authDomain: 'shopping-app-cdbe4.firebaseapp.com',
    storageBucket: 'shopping-app-cdbe4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVNtF9p3_bumZvG4W_jptel3wjmOzUIM',
    appId: '1:26260141407:android:c5f1bf7741438261f532ea',
    messagingSenderId: '26260141407',
    projectId: 'shopping-app-cdbe4',
    storageBucket: 'shopping-app-cdbe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz34_oVqtbBl7xAsfQPTFR-1-JkNEAsXc',
    appId: '1:26260141407:ios:ee2077a4efe96e72f532ea',
    messagingSenderId: '26260141407',
    projectId: 'shopping-app-cdbe4',
    storageBucket: 'shopping-app-cdbe4.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz34_oVqtbBl7xAsfQPTFR-1-JkNEAsXc',
    appId: '1:26260141407:ios:ee2077a4efe96e72f532ea',
    messagingSenderId: '26260141407',
    projectId: 'shopping-app-cdbe4',
    storageBucket: 'shopping-app-cdbe4.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvFARMbet950EVGuekismUM0wDp3knFkQ',
    appId: '1:26260141407:web:f1e3bb3856d16802f532ea',
    messagingSenderId: '26260141407',
    projectId: 'shopping-app-cdbe4',
    authDomain: 'shopping-app-cdbe4.firebaseapp.com',
    storageBucket: 'shopping-app-cdbe4.firebasestorage.app',
  );
}
